/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import Main.GuardarTexto;
import Main.Juego;

/**
 *
 * @author soviedog
 */
public class ParteGraficaJuego extends javax.swing.JFrame {
 private final Juego m = new Juego();
    /**
     * Creates new form ParteGraficaJuego
     */
    public ParteGraficaJuego() {
        initComponents();
         this.whoWin.setText("-");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piedra = new javax.swing.JButton();
        papel = new javax.swing.JButton();
        tijera = new javax.swing.JButton();
        lagarto = new javax.swing.JButton();
        whoWin = new javax.swing.JLabel();
        scorePlayer = new javax.swing.JLabel();
        scoreComputer = new javax.swing.JLabel();
        sacaPlayer = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        sacaComputer = new javax.swing.JLabel();
        marcador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArchivo = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        chkAgregarTexto = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piedra.png"))); // NOI18N
        piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piedraActionPerformed(evt);
            }
        });
        getContentPane().add(piedra);
        piedra.setBounds(40, 170, 100, 60);

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papel.png"))); // NOI18N
        papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelActionPerformed(evt);
            }
        });
        getContentPane().add(papel);
        papel.setBounds(180, 170, 100, 60);

        tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tijeras.png"))); // NOI18N
        tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tijeraActionPerformed(evt);
            }
        });
        getContentPane().add(tijera);
        tijera.setBounds(40, 250, 100, 90);

        lagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lagarto.png"))); // NOI18N
        lagarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lagartoActionPerformed(evt);
            }
        });
        getContentPane().add(lagarto);
        lagarto.setBounds(180, 250, 100, 90);

        whoWin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        whoWin.setForeground(new java.awt.Color(255, 255, 255));
        whoWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(whoWin);
        whoWin.setBounds(10, 20, 710, 110);

        scorePlayer.setBackground(new java.awt.Color(255, 51, 51));
        scorePlayer.setForeground(new java.awt.Color(255, 0, 0));
        scorePlayer.setText("0");
        getContentPane().add(scorePlayer);
        scorePlayer.setBounds(50, 60, 20, 16);

        scoreComputer.setForeground(new java.awt.Color(255, 102, 102));
        scoreComputer.setText("0");
        getContentPane().add(scoreComputer);
        scoreComputer.setBounds(600, 50, 20, 16);
        getContentPane().add(sacaPlayer);
        sacaPlayer.setBounds(300, 200, 130, 80);

        player2.setForeground(new java.awt.Color(255, 0, 0));
        player2.setText("Player 2");
        getContentPane().add(player2);
        player2.setBounds(590, 30, 60, 16);

        player1.setForeground(new java.awt.Color(255, 51, 51));
        player1.setText("Player 1");
        getContentPane().add(player1);
        player1.setBounds(30, 30, 90, 20);
        getContentPane().add(sacaComputer);
        sacaComputer.setBounds(550, 200, 150, 90);

        marcador.setForeground(new java.awt.Color(255, 51, 0));
        marcador.setText("/");
        getContentPane().add(marcador);
        marcador.setBounds(310, 40, 120, 16);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("VS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 190, 70, 80);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos"));
        jPanel4.setLayout(null);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardar);
        btnGuardar.setBounds(460, 70, 126, 24);

        txtArchivo.setColumns(20);
        txtArchivo.setRows(5);
        jScrollPane1.setViewportView(txtArchivo);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(50, 30, 385, 83);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizar);
        btnActualizar.setBounds(460, 110, 126, 24);

        chkAgregarTexto.setText("Agregar Texto");
        jPanel4.add(chkAgregarTexto);
        chkAgregarTexto.setBounds(470, 30, 103, 24);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(190, 450, 610, 140);

        jPanel2.setLayout(null);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jPanel2.add(fondo);
        fondo.setBounds(-930, -210, 2100, 1110);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1030, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piedraActionPerformed
      
       int valorMaquina = m.turnoMaquina();
       this.sacaPlayer.setIcon(m.traductorTurnero(0));
       this.sacaPlayer.repaint();
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
       String Ganador = m.versus(0, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    
    }//GEN-LAST:event_piedraActionPerformed

    private void papelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelActionPerformed
        // TODO add your handling code here:
       int valorMaquina = m.turnoMaquina();
       this.sacaPlayer.setIcon(m.traductorTurnero(1));
       this.sacaPlayer.repaint();
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
       String Ganador = m.versus(1, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_papelActionPerformed

    private void tijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tijeraActionPerformed
        // TODO add your handling code here:
       int valorMaquina = m.turnoMaquina();
       this.sacaPlayer.setIcon(m.traductorTurnero(2));
       this.sacaPlayer.repaint();
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
       String Ganador = m.versus(2, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_tijeraActionPerformed

    private void lagartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lagartoActionPerformed
        // TODO add your handling code here:
       int valorMaquina = m.turnoMaquina();
       this.sacaPlayer.setIcon(m.traductorTurnero(3));
       this.sacaPlayer.repaint();
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
       String Ganador = m.versus(3, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_lagartoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
         GuardarTexto documento = new   GuardarTexto();

        documento.Escribir("Puntaje de jugador 1: "+scorePlayer.getText() +" Puntaje de Computadora: "+scoreComputer.getText() ,
            chkAgregarTexto.isSelected());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

       GuardarTexto documento = new  GuardarTexto();

        txtArchivo.setText(documento.Leer());
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParteGraficaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParteGraficaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParteGraficaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParteGraficaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParteGraficaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkAgregarTexto;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lagarto;
    private javax.swing.JLabel marcador;
    private javax.swing.JButton papel;
    private javax.swing.JButton piedra;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    private javax.swing.JLabel sacaComputer;
    private javax.swing.JLabel sacaPlayer;
    private javax.swing.JLabel scoreComputer;
    private javax.swing.JLabel scorePlayer;
    private javax.swing.JButton tijera;
    private javax.swing.JTextArea txtArchivo;
    private javax.swing.JLabel whoWin;
    // End of variables declaration//GEN-END:variables
}
